### ISSUE TITLE
Stream-library-agnostic operator toolkit

### ISSUE THREAD

**Issue by axefrog** [frptools/salix#23]
In order to promote agnosticism with respect to the stream library that a developer wishes to use, Salix will (at this stage) be using a stream provider of sorts. This will be a wrapper that internally takes a dependency on an library-specific adapter. The adapter will mainly be used for stream graph construction, and not usually invoked as a result of general data flow within the application. Data will be primarily flowing through a stream graph which is native to the stream library in question, but constructed using the stream provider. In other words, the design will allow stream library agnosticism without being a dataflow bottleneck.

_**Note:** Direct use of a specific stream library such as Most.js will still be standard in any consuming application, just as it is now. The adapter layer will only be used internally within Salix, and by developers who wish to distribute reusable components and modules. Components can still be library-specific if desired, but redistributability will be reduced as a result._

**Pros:**

- Developers of components and modules can use the toolkit to cover their stream-related needs and not worry about impedance mismatches between different stream libraries.
- Promotes a healthier ecosystem by making it possible for enthusiasts of different stream libraries to develop components and modules that can be shared irrespective of stream library, and without removing the power to code using streams.
- Use of the best observable model for the environment in question will be a solved problem; e.g. FuseTools has its own oddly-designed observable library which is linked directly into the binaries that they deploy to mobile, so it makes sense to be able to use that as much as possible if using Salix to manage a mobile app.

**Cons:**

- Need to decide on a suitable common set of operators before initial release
- Need to deal with potential inconsistencies in the way a common operator is assumed to work in two different libraries.
- Possible minor performance impact if used without care.
- Additional code footprint to support the abstraction

### Design

A set of operators would be exposed and curried with the following signature:

```js
operator(adapter, ...functionality, ...inputs)
```

- **adapter:** used to return library-specific streams based on subsequent inputs
- **functionality:** curryable values that define the operator's behaviour; e.g. a mapping function
- **inputs:** the inputs that will change most frequently; usually one or more streams defining sources

Example "universal" operators would be: `map`, `filter`, `flatMap`, etc.

The provider instance that you'd have access to for developing a distributable component or module. would expose a number of independent functions (i.e. feel free to destructure without loss of context), pre-curried with the relevant adapter. Their design would assume two possible cases: (a) curried invocation to define behaviour but not input, and (b) calling directly with inputs/streams, bypassing the intermediate currying step.

**Examples:**

```js
const {map, filter, combine, pipe} = provider;
const mapToString = map(x => x.toString());
const notNil = filter(x => x !== void 0 && x !== null);
const data$ = notNil(upstream$);
const str$ = mapToString(data$);

// less currying...
const num$ = filter(x => !isNaN(x), map(x => parseInt(x), data$));

// alternative to the lack of fluent interface:
const foo$ = pipe([
  map(toFrog),
  filter(greenOnly),
  map(toToad)
]);
```

Would really appreciate some input/feedback @TylorS  and @Frikki - feel free to hate on the whole idea and demand a hard dependency on Most.js ;)

Which universal operators do you think would be most important to expose to module/component authors, and which do you think might be a problem with respect to inconsistent or unexpected differences in behaviour between stream libraries?

**Comment by TylorS** [comment]
I've definitely tried to do something like this before, let me see if I uploaded it to github, I definitely ran into issues but can't remember what they were.

**Comment by TylorS** [comment]
I doesn't look like I ever uploaded anything to GitHub, and can't find any trace of it on my hard drive. I'm definitely in favor of this in general as I definitely like the idea of sharing with others and being able to reuse work where possible. 

On the other hand though, to be fair, the cost of these abstractions are also placed on those who may author different things for Salix, and *can* be a hassle as it has been for people and stream adapters in Cycle.js.

**Comment by axefrog** [comment]
Hey Tylor, thanks for the reply.

> the cost of these abstractions are also placed on those who may author different things for Salix, and can be a hassle as it has been for people and stream adapters in Cycle.js.

Could you elaborate a little? There were a few points there that I thought might make it less of a concern, and the alternative has its own downsides. I'd also encourage you not to map the word "adapter" too closely to what you were doing with Cycle; there are likely some significant differences and the similariy may be in name only.

**Comment by TylorS** [comment]
Definitely...

I think I understand the obvious differences between what you're defining as an adapter and what Cycle uses for adapters, but I think there is still a conceptual correlation between them. In particular additional abstractions are an additional thing to document, another data point that needs to be retrieved before being able to properly provide support and probably most importantly abstractions are an additional thing for users to learn on top of already trying to learn a new library (Salix).

Between the core Cycle.js devs these days, we all generally agree that supporting multiple stream libraries was actually one of the worse decisions we made. This is largely due to the difficulty of supporting users with issues (e.g one may not be familiar with the quirks of library foo), and especially the overhead of maintaining official support of these different libraries.

I'm not saying that these "cons" are enough to through away the whole idea, I'm definitely not saying that, I just feel they have been valid data points to abstractions I've dealt with in the past, and should be weighed in on. I'm still generally in favor of abstraction and agnosticism, but I'm much more wary of the effect they can have on maintenance and support! 

If any of these are null and void in a way that I'm missing, feel free to point it out. :smile:

**Comment by axefrog** [comment]
> Between the core Cycle.js devs these days, we all generally agree that supporting multiple stream libraries was actually one of the worse decisions we made. This is largely due to the difficulty of supporting users with issues (e.g one may not be familiar with the quirks of library foo), and especially the overhead of maintaining official support of these different libraries.

That's a great point, thanks for the additional info!

**Comment by axefrog** [comment]
I'm going to take a hard dependency on Most at this stage. Thanks for weighing in!

**Comment by Frikki** [comment]
Just to add my POV. It shouldn’t be the responsibility of the library to provide adapters. Instead, it should be the client’s responsibility to make adapters should he decide to use a different stream library. It should, hypothetically, be fairly easy to accomplish.

**Comment by axefrog** [comment]
Agreed, in retrospect.
